# To start a hub, run:
#
#   docker compose run hubble yarn identity create
#   docker compose up hubble
#
# If you want your hub to support grpc-web, you can also run
#
#   docker compose up envoy
#
# This can be useful when playing with hubs locally.

version: '3.9'

services:
  hubble:
    build:
      context: .
      dockerfile: Dockerfile.hubble
    ports:
      - '2282:2282'
      - '2283:2283'
      - '2284:2284'
    volumes:
      - ./apps/hubble/.hub:/home/node/app/apps/hubble/.hub
      - ./apps/hubble/.rocks:/home/node/app/apps/hubble/.rocks
    networks:
      - my-network

  envoy:
    image: envoyproxy/envoy:v1.26.1
    ports:
      - '2285:2285'
      - '9901:9901'
    volumes:
      - ./apps/hubble/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - my-network

networks:
  my-network:
