{
 "title": "Hubble Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Hub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Merge Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.hubble.hub.merge_message.mean"
    }
   ]
  },
  {
   "title": "Sync Engine Sync time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "target": "stats.timers.hubble.syncengine.sync_time_ms.mean"
    }
   ]
  },
  {
   "title": "Node Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "target": "stats.gauges.hubble.merkle_trie.num_messages"
    },
    {
     "target": "stats.gauges.hubble.rocksdb.approximate_size"
    }
   ]
  },
  {
   "title": "Num Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(stats.gauges.hubble.gossip.peers.*)"
    }
   ]
  },
  {
   "title": "Blocked Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.denied_peers"
    }
   ]
  },
  {
   "title": "Merkle Trie Queue Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.merkle_trie.merge_q"
    }
   ]
  },
  {
   "title": "Merge Queue Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.syncengine.merge_q"
    }
   ]
  },
  {
   "title": "Gossip Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.peers.inbound"
    },
    {
     "target": "stats.gauges.hubble.gossip.peers.outbound"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "target": "stats_counts.hubble.gossip.messages"
    }
   ]
  },
  {
   "title": "Inbound Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.peers.inbound"
    }
   ]
  },
  {
   "title": "Inbound Sync",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats_counts.hubble.rpc.get_sync_snapshot"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "Errors by Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "sumSeriesWithWildcards(stats_counts.hubble.submit_message.error.*.*.*, 5,6)"
    }
   ]
  },
  {
   "title": "Errors by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "target": "sumSeriesWithWildcards(stats_counts.hubble.submit_message.error.*.*.*, 4,5)"
    }
   ]
  }
 ]
}