name: Label Issues

on:
  issues:
    types: [opened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['s-triage']
            })
