name: Publish Replicator
on:
  push:
    tags:
      - '@farcaster/replicator@*'

concurrency: package-tags

jobs:
  publish-docker-image:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in so we can push the image layers + tags to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.FARCASTERXYZ_DOCKER_HUB_USER }}
          password: ${{ secrets.FARCASTERXYZ_DOCKER_HUB_TOKEN }}

      - uses: depot/setup-action@v1

      - run: ./scripts/publish-replicator-image.sh
        shell: bash
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
          DEPOT_PROJECT_ID: ${{ secrets.DEPOT_PROJECT_ID }}
